#!/bin/bash
shopt -s nullglob
. ${CONF_FILE}
sassc_func(){ 
	echo "sassc"
	if command -v sassc > /dev/null 2>&1; then
		SASS=sassc
	elif [ -x './build_tools/sources/sassc/bin/sassc' ]; then
		SASS='./build_tools/sources/sassc/bin/sassc'
	else
		echo "At this moment, the only sass tool build_scripts/css supports is sassc. You can install it yourself or build the submodule in the build_tools directory, or modify build_scripts/css."
		echo 'At time of writing (Aug 2019), cloning github.com/sass/sassc, running `. scripts/bootstrap` inside of it, and `make` is enough. It created two folders:sass-spec and libsass in the same directory as sassc, which can be deleted safely.'
		return
	fi

	sudo -E -u nobody -- mkdir -p ${OUTPUT_DIR}/css
	for filename in ${ROOT_DIR}/sass/*.scss; do
		if [ -r "$filename" ] && [ -f "$filename" ]; then
			filename=$(realpath $filename)
			output=$(realpath ${OUTPUT_DIR}/css)/$(basename ${filename})
			output=${output%.scss}.css
			sudo -E -u nobody -- ${SASS} ${filename} ${output}
		fi
	done
}
sassc_func

prefixer(){
	echo "prefixing"
	if [ -e ${ROOT_DIR}/build_tools/toolchain/prefixer/package-lock.json ]; then
		if ! ls -A ${OUTPUT_DIR}/css/*.css > /dev/null 2>&1; then
			return
		fi
		if command -v npx > /dev/null 22>&1; then
			pushd ${ROOT_DIR}/build_tools/toolchain/prefixer/
			sudo -E -u nobody -- npx postcss ${OUTPUT_DIR}/css/*.css --no-map --use autoprefixer -d ${OUTPUT_DIR}/css/
			popd
		else
			echo "npx not found"
			return
		fi
	else 
		echo 'prefixer not found in in build_tools/tool_chain/prefixer- `npm install postcss-cli autoprefixer` maybe?'
	fi
}
prefixer
