#!/bin/bash
shopt -s nullglob
. ${CONF_FILE}

eslint_func(){
	echo "eslint"
	if [ -e ${ROOT_DIR}/build_tools/toolchain/eslint/package-lock.json ]; then
		shopt -u nullglob
		if ! ls -A ${ROOT_DIR}/raw/js/*.js > /dev/null 2>&1; then
			echo "No javascript files"
			shopt -s nullglob
			return
		fi
			shopt -s nullglob
		if command -v npx > /dev/null 22>&1; then
			pushd ${ROOT_DIR}/build_tools/toolchain/eslint/
			sudo -E -u nobody -- npx eslint -c ${ROOT_DIR}/build_tools/toolchain/eslint/.eslintrc.yml ${ROOT_DIR}/raw/js/**
			popd
		else
			echo "npx not found"
			return
		fi
	else 
		echo 'eslint not found, check its readme in that folder in build_tools/toolchain'
	fi
}
eslint_func
