#!/bin/bash
shopt -s nullglob

if [ -f "${ROOT_DIR}/conf/common.conf" ]; then
	. "${ROOT_DIR}/conf/common.conf"
else
	. "${ROOT_DIR}/conf/common.conf.default"
fi
OUTPUT_DIR=${ROOT_DIR}/compiled

webpack_func(){  # also look for npx TODO
	if [ -e ${ROOT_DIR}/build_tools/toolchain/webpack/package-lock.json ]; then
		shopt -u nullglob
		DEBUG_LINE=''
		if [ "${WEBPACK_MODE}" = "\"development\"" ]; then
			DEBUG_LINE='--debug --devtool "inline-source-map"'
		fi
		if ls -A ${ROOT_DIR}/ts/*.ts 2> /dev/null || ls -A ${ROOT_DIR}/ts/**/*.ts 2> /dev/null; then
			shopt -s nullglob
			pushd ${ROOT_DIR}/build_tools/toolchain/webpack/
			npx webpack --mode "${WEBPACK_MODE}" $DEBUG_LINE --entry "${ROOT_DIR}/ts/main.ts" --output "${OUTPUT_DIR}/js/bundle.js" --config "${ROOT_DIR}/build_tools/toolchain/webpack/webpack.tsconfig.js"
			popd
		elif ls -A ${ROOT_DIR}/js/*.js 2> /dev/null || ls -A ${ROOT_DIR}/js/**/*.js 2> /dev/null; then
			shopt -s nullglob
			pushd ${ROOT_DIR}/build_tools/toolchain/webpack/
			npx webpack --mode "${WEBPACK_MODE}" $DEBUG_LINE --entry "${ROOT_DIR}/js/main.js" --output "${OUTPUT_DIR}/js/bundle.js"
			popd
		else
			echo "Appears there is no javascript to process"
			return 0
		fi
		shopt -s nullglob
	else
		echo "Webpack not found, assuming not used." 
		return 1
	fi
	return 0
}

tsc_func(){ 
	if ! command -v tsc > /dev/null 2>&1; then
		echo "To compile typescript, you're expected to install node-typescript in a normal way."
		echo "You're using vanilla javascript? Peasant."
		return
	fi
	echo "tsc- warning: sourceMap options untested (debugging). Should allow debugging in original"
	echo "Typescript instead of what is compiled to. Definitely works with webpack"
	mkdir -p "${OUTPUT_DIR}/js" || exit
	tsc --inlineSourceMap --inlineSources -p "${ROOT_DIR}/ts/" --outDir "${OUTPUT_DIR}/js/"
}
if ! webpack_func; then
	tsc_func
fi
