#!/bin/bash

. ${CONF_FILE}
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

#check list (link):
#html X
#bootstrap X
#svg X
#css X
#javascript
#wasm
#jpg
#png

echo -e "${RED}THE OPTIMIZER SCRIPT CAN BE EXPANDED TO LINT WASM${NC}"
echo -e "${RED}IT CAN LOOK FOR BROKEN LINKS BUT THAT WOULD BE ANNOYING IN DEV${NC}"
echo -e "${RED}IT CAN MINIFY AND COMPRESS AND SPEED CHECK TOO${NC}"
echo -e "${RED}BUT THIS NEEDS TO BE FLAGGABLE AS SAID${NC}"
echo -e "${RED}**********************************************************${NC}"

echo "OUTPUT_DIR: ${OUTPUT_DIR}"
if [ -z "${OUTPUT_DIR}" ]; then
	echo -e "${RED}You need to define OUTPUT_DIR so I know what to lint!${NC}"
	exit
fi

if [ -z "${ROOT_DIR}" ]; then
	echo -e "${RED}You need to define ROOT_DIR so I know what to lint!${NC}"
	exit
fi

function HTMLBasic {
	echo -e "${GREEN}Checking... html $1 w/ validator.w3.org${NC}"
	curl -H "Content-type: text/html; charset=utf-8" \
		--data-binary @${1} \
		https://validator.w3.org/nu/?out=gnu 
	if command -v aspell &> /dev/null; then
		for line in $(cat "${1}" | aspell -H list); do
			if [ ! -f "${ROOT_DIR}/build_tools/dictionary" ]; then
				touch "${ROOT_DIR}/build_tools/dictionary"
			fi
			if ! grep -q "${ROOT_DIR}/build_tools/dictionary" -e "^$line\$"; then
				echo ${1}: $line
				if [ "$INTERACTIVE" = "true" ]; then
					echo "Add ${line} to dict? Y/n"
					read ANSW
					if [ "$ANSW" = "y" ] || [ "$ANSW" = "Y" ]; then
						echo "$line" >> "${ROOT_DIR}/build_tools/dictionary"
					fi
				fi
			fi
		done
	else
		echo "Install aspell for spellcheck"
	fi
}

function SVGBasic {
 echo -e "${GREEN}Checking... svg $1 w/ validator.w3.org${NC}"
 curl -H "Content-type: image/svg+xml; charset=utf-8" \
	 --data-binary @${1} \
	 https://validator.w3.org/nu/?out=gnu 
}

function CSSBasic {
 echo -e "${GREEN}Checking... csd $1 w/ validator.w3.org${NC}"
 curl -H "Content-type:text/css; charset=utf-8" \
	 --data-binary @${1} \
	 https://validator.w3.org/nu/?out=gnu 
}

# For just HTML
(
shopt -s globstar
for file in ${OUTPUT_DIR}/**/*.html; do
	if [ -z "$file" ]; then
		continue
	fi
	HTMLBasic $file 2>&1 #i don't really want linters throwing errors so i redirect all error output to standard output
done 
)

while read -r file; do
	if [ -z "$file" ]; then
		continue
	fi
	CSSBasic $file 2>&1
done <<< "$(find ${OUTPUT_DIR} -type f -name *.css)"

while read -r file; do
	if [ -z "$file" ]; then
		continue
	fi
	SVGBasic $file 2>&1
done <<< "$(find ${OUTPUT_DIR} -type f -name *.svg)"
