#!/bin/bash
set -e
# Set Input Dir

if [ -f "${ROOT_DIR}/conf/common.conf" ]; then
	. "${ROOT_DIR}/conf/common.conf"
else
	. "${ROOT_DIR}/conf/common.conf.default"
fi

if [ -z "${1}" ]; then
	INPUT_DIR="${ROOT_DIR}/raw"
else
	INPUT_DIR="${1}"
fi


if command -v contate > /dev/null 2>&1; then
	CONTATE=contate
elif [ -x ./build_tools/sources/contate/build/contate ]; then
	CONTATE="${ROOT_DIR}/build_tools/sources/contate/build/contate"
	alias contate="${CONTATE}"
else
	echo "Contate not found! Check README.md! *.contate files won't work!"
fi

if [ ! -d "${OUTPUT_DIR}" ]; then
	echo "Output directory doesn\'t exist"
	echo "${OUTPUT_DIR}"
	exit 1
fi
if [ ! -z "${CONTATE}" ]; then
	${CONTATE} -r -o ${OUTPUT_DIR}/ ${INPUT_DIR}/
fi

rsync -rit --exclude '*.contate' --exclude '.*' ${INPUT_DIR}/ ${OUTPUT_DIR}/

