#!/bin/bash
shopt -s nullglob
. ${CONF_FILE}
tsc_func(){ 
	echo "tsc"
	if ! command -v tsc > /dev/null 2>&1; then
		echo "To compile typescript, you're expected to install node-typescript in a normal way"
		return
	fi
	sudo -E -u nobody -- mkdir -p "${OUTPUT_DIR}/js" || exit
	sudo -E -u nobody -- tsc -p "${ROOT_DIR}/ts/" --outDir "${OUTPUT_DIR}/js/"
}
tsc_func
